### ISSUE TITLE
AtherysRPG skill nodes editor

### ISSUE THREAD

**Issue by fingoltin** [Atherys-Horizons/AtherysDocs#5]
# Overview
We need an editor for creating AtherysRPG skill trees, as the configuration can get quite complicated. This will take more effort than the item editor or the quest editor.
### Skills (Vertices)
* ID (skill name)
* Cost 
* Cooldown

### Skill Links (Edges)
* Parent Skill
* Child Skill
* Cost (weight)
* Type (Bi-directional or Uni-directional)

### Features
* Adding & removing skill nodes
* Adding & removing skill links
* Modifying skills 
* Modifying skill links

#### Tasks
- [x] Explore graph visualization libraries
- [x] Read from config file
- [x] Write to config file
- [x] Create menus for editing skills and skill links
- [x] Render skills and skill links with Vis
- [x] Connect visual graph to skills and skill links

**Comment by fingoltin** [comment]
Library found: [Vis](http://visjs.org/index.html#modules).
